services:
  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile

    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./back:/corazonVirtual/backend
    depends_on:
      - postgres
    networks:
      - app

  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    restart: always
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      
    tty: true

    ports:
      - 3000:3000

    volumes:
      - ./front:/corazonVirtual/frontend

    depends_on:
      - backend

    networks:
      - app

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres
    networks:
      - app

networks:
    app:
      driver: bridge